server:
  port: 50500
spring:
  application:
    name: spider-executor


xxl:
  job:
    accessToken: ''
    admin:
      addresses: http://127.0.0.1:8055/xxl-job-admin
    executor:
      address: ''
      appname: spider-executor
      ip: '127.0.0.1'
      logpath: /data/applogs/xxl-job/jobhandler
      logretentiondays: 30
      port: 50501
